=== Rafael-Pieri/xml-alura/src/main/resources/sales-form.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xsi:noNamespaceSchemaLocation="sales-form.xsd"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

	<xsd:element name="sales">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="paymentForm" type="xsd:string" />
				<xsd:element name="products">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element ref="product" maxOccurs="unbounded" />
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
			</xsd:sequence>
			<xsd:attribute name="currency" type="xsd:string" />
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="product">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="name" type="xsd:string" />
				<xsd:element name="price" type="xsd:double" />
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>

</xsd:schema>

=== Rafael-Pieri/xml-alura/src/main/resources/sales.xml
<?xml version="1.0" encoding="UTF-8"?>
<sales currency="real" xsi:noNamespaceSchemaLocation="sales-form.xsd"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<paymentForm>Debit</paymentForm>
	<products>
		<product>
			<name>Xml book</name>
			<price>29.00</price>
		</product>
		<product>
			<name>Java book</name>
			<price>19.00</price>
		</product>
		<product>
			<name>Spring book</name>
			<price>23.00</price>
		</product>
	</products>
</sales>
